export const QUIZ_ACTIONS = {
  START_QUIZ: "START_QUIZ",
  ANSWER_QUESTION: "ANSWER_QUESTION",
  GO_BACK: "GO_BACK",
  GO_FORWARD: "GO_FORWARD",
  GO_TO_EMAIL: "GO_TO_EMAIL",
  GO_TO_EMAIL_FROM_QUESTION: "GO_TO_EMAIL_FROM_QUESTION",
  SUBMIT_EMAIL: "SUBMIT_EMAIL",
  RESTART_QUIZ: "RESTART_QUIZ",
  LOAD_STATE: "LOAD_STATE",
  SET_LOADED: "SET_LOADED",
};
